# Generated by Django 5.0.6 on 2024-06-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='authapp.service'),
        ),
    ]
