# Generated by Django 5.0.6 on 2024-06-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_created_at_order_date_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Default Service Name', max_length=255),
        ),
    ]
